import json
import locale
import sys
from reportlab.platypus import SimpleDocTemplate
import os
from reportlab.platypus import Paragraph, Spacer, Table, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from email.message import EmailMessage
import emails
import mimetypes

message = EmailMessage()
table_style = [('GRID', (0,0), (-1,-1), 1, colors.black)]
styles = getSampleStyleSheet()

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  locale.setlocale(locale.LC_ALL, 'en_US.UTF8')
  max_revenue = {"revenue": 0}
  most_pop = {}
  max_sale = {"total_sales" : 0}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item


    if item["total_sales"] > max_sale["total_sales"]:
      max_sale = item

    # TODO: also handle most popular car_year

    k = item["car"]["car_year"]
    most_pop[k] = most_pop.get(k,0) + item["total_sales"]

  maximum = max(most_pop.values())
  maxyear = 0
  for i in most_pop:
      if most_pop[i] == maximum:
          maxyear = i
          break

  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(
      format_car(max_sale["car"]), max_sale["total_sales"]),
    "The most popular year was {} with {} sales.".format(
      maxyear, maximum)
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  # TODO: turn this into a PDF report
  report = SimpleDocTemplate("/tmp/cars.pdf")
  #report = SimpleDocTemplate(os.path.join(os.getcwd(),'cars.pdf'))
  report_title = Paragraph("Sales Summary of Last Month", styles["h1"])
  k = [report_title]
  for i in summary:
    report_body = Paragraph(i, styles["h5"])
    k.append(report_body)

  table_data = cars_dict_to_table(data)
  report_table = Table(data=table_data, style=table_style, hAlign="LEFT")
  k.append(report_table)
  report.build(k)
  # Writing content of email.
  sender = "automation@example.com"
  receiver = "{}@example.com".format(os.environ.get('USER'))
  subject = "Sales summary for last month"
  body = "\n".join(summary)

  message = emails.generate(sender, receiver, subject, body, "/tmp/cars.pdf")
  # TODO: send the PDF report as an email attachment
  emails.send(message)

if __name__ == "__main__":
  main(sys.argv)
